import { useState } from 'react';
import { motion } from 'framer-motion';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';
const GLASS = { background:'rgba(255,255,255,0.55)', backdropFilter:'blur(18px)', WebkitBackdropFilter:'blur(18px)', border:'1px solid rgba(255,255,255,0.25)', boxShadow:'0 8px 32px rgba(31,41,55,0.08)' };
const DATA = [{m:'Jan',searches:1200,bookings:340},{m:'Feb',searches:1500,bookings:420},{m:'Mar',searches:1900,bookings:580},{m:'Apr',searches:2100,bookings:650},{m:'May',searches:2600,bookings:820},{m:'Jun',searches:3100,bookings:980}];
const SEASONS = [{s:'Summer',domestic:65,intl:35},{s:'Monsoon',domestic:80,intl:20},{s:'Winter',domestic:45,intl:55},{s:'Spring',domestic:70,intl:30}];
const TOP = [{name:'Bali',score:98},{name:'Goa',score:95},{name:'Paris',score:92},{name:'Dubai',score:89},{name:'Tokyo',score:86}];
export default function Analytics() {
  return (
    <motion.div className="space-y-6" initial={{ opacity:0, y:16 }} animate={{ opacity:1, y:0 }}>
      <div><h1 className="page-title">Analytics and Trends</h1><p className="page-subtitle">Platform performance insights</p></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <div className="rounded-3xl p-6" style={GLASS}><h3 className="font-bold font-display mb-1" style={{ color:'#1F2937' }}>Search vs Bookings</h3><p className="text-xs mb-4" style={{ color:'#9CA3AF' }}>Monthly comparison</p><ResponsiveContainer width="100%" height={220}><AreaChart data={DATA}><defs><linearGradient id="as" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2E7D6B" stopOpacity={0.3}/><stop offset="95%" stopColor="#2E7D6B" stopOpacity={0}/></linearGradient><linearGradient id="ab" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0369A1" stopOpacity={0.2}/><stop offset="95%" stopColor="#0369A1" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(124,154,126,0.1)"/><XAxis dataKey="m" tick={{ fontSize:11, fill:'#9CA3AF' }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize:11, fill:'#9CA3AF' }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background:'#fff', border:'1px solid #EFEDE7', borderRadius:12, fontSize:12 }}/><Area type="monotone" dataKey="searches" stroke="#2E7D6B" strokeWidth={2} fill="url(#as)" name="Searches"/><Area type="monotone" dataKey="bookings" stroke="#0369A1" strokeWidth={2} fill="url(#ab)" name="Bookings"/></AreaChart></ResponsiveContainer></div>
        <div className="rounded-3xl p-6" style={GLASS}><h3 className="font-bold font-display mb-1" style={{ color:'#1F2937' }}>Seasonal Travel</h3><p className="text-xs mb-4" style={{ color:'#9CA3AF' }}>Domestic vs International</p><ResponsiveContainer width="100%" height={220}><BarChart data={SEASONS}><CartesianGrid strokeDasharray="3 3" stroke="rgba(124,154,126,0.1)"/><XAxis dataKey="s" tick={{ fontSize:11, fill:'#9CA3AF' }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize:11, fill:'#9CA3AF' }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background:'#fff', border:'1px solid #EFEDE7', borderRadius:12, fontSize:12 }}/><Bar dataKey="domestic" fill="#2E7D6B" radius={[4,4,0,0]} name="Domestic"/><Bar dataKey="intl" fill="#A7C4A0" radius={[4,4,0,0]} name="International"/></BarChart></ResponsiveContainer></div>
      </div>
      <div className="rounded-3xl p-6" style={GLASS}><h3 className="font-bold font-display mb-4" style={{ color:'#1F2937' }}>Top Performing Destinations</h3><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{TOP.map(d => <div key={d.name} className="rounded-2xl p-4 text-center" style={{ background:'rgba(46,125,107,0.08)', border:'1px solid rgba(124,154,126,0.15)' }}><p className="font-bold text-xl" style={{ color:'#2E7D6B' }}>{d.score}</p><p className="text-xs font-semibold mt-1" style={{ color:'#6B7280' }}>{d.name}</p></div>)}</div></div>
    </motion.div>
  );
}